version: '3'
services:

  database:
    build: ./database
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - backnet

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - database
    ports:
      - 5001:80
    networks:
      - backnet

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 5002:80
    networks:
      - backnet
      - frontnet

networks:
  backnet:
    driver: bridge
  frontnet:
    driver: bridge
